#!/usr/bin/env bash
# Downloads the third-party files the E2E kit needs into e2e/work/cache (override with E2E_CACHE). Idempotent:
# files that are already there with the right SHA-256 are kept. run_e2e.sh calls this itself.
#
#   fetch.sh [server] [mods] [velocity] [jre25]      default: server mods
#
#   server    Fabric server launcher for 1.21.11 / Loader 0.19.5, plus a server template (the launcher's first run
#             downloads and remaps Minecraft, which every scenario then reuses). Needs ACCEPT_EULA=true.
#   mods      Fabric API, Polymer (bundled), FabricProxy-Lite
#   velocity  Velocity 4.2.0 (needs Java 25)
#   jre25     a Temurin 25 JRE for Velocity, unless VELOCITY_JAVA or a JAVA_HOME of a Java 25+ already provides one
set -euo pipefail

E=$(cd "$(dirname "$0")" && pwd)
CACHE=${E2E_CACHE:-$E/work/cache}
JAVA=${JAVA:-java}
mkdir -p "$CACHE"

LAUNCHER=fabric-server-launch-1.21.11-0.19.5.jar
FABRIC_API=fabric-api-0.141.6+1.21.11.jar
POLYMER=polymer-bundled-0.15.2+1.21.11.jar
FPL=FabricProxy-Lite-2.11.0.jar
VELOCITY=velocity-4.2.0-30.jar

# fetch <file name in cache> <url> <sha256>
fetch() {
  local file=$CACHE/$1
  if [ -f "$file" ] && [ "$(sha256sum "$file" | cut -d' ' -f1)" = "$3" ]; then
    return
  fi
  echo "fetch.sh: downloading $1"
  curl -fsSL --retry 3 -o "$file.part" "$2"
  if [ "$(sha256sum "$file.part" | cut -d' ' -f1)" != "$3" ]; then
    rm -f "$file.part"
    echo "fetch.sh: checksum mismatch for $1 (downloaded from $2)" >&2
    exit 1
  fi
  mv "$file.part" "$file"
}

fetch_server() {
  # The launcher is generated by meta.fabricmc.net for game 1.21.11, loader 0.19.5, installer 1.1.2.
  fetch "$LAUNCHER" "https://meta.fabricmc.net/v2/versions/loader/1.21.11/0.19.5/1.1.2/server/jar" \
    2b63d293be54c8f5484a242859cab841dcee38511e11b2f82e92211f19872d08
  local template=$CACHE/server-template
  if [ -d "$template/libraries" ] && [ -d "$template/versions" ]; then
    return
  fi
  if [ "${ACCEPT_EULA:-}" != "true" ]; then
    echo "fetch.sh: running a Minecraft server means accepting the Minecraft EULA (https://aka.ms/MinecraftEULA)." >&2
    echo "          Re-run with ACCEPT_EULA=true if you accept it." >&2
    exit 1
  fi
  echo "fetch.sh: preparing the server template (downloads and remaps Minecraft 1.21.11, takes a minute)"
  rm -rf "$template"
  mkdir -p "$template"
  cp "$CACHE/$LAUNCHER" "$template/fabric-server-launch.jar"
  echo "eula=true" > "$template/eula.txt"
  # --initSettings makes the server write its settings files and exit before it loads a world.
  (cd "$template" && "$JAVA" -jar fabric-server-launch.jar nogui --initSettings > launch.log 2>&1) || {
    echo "fetch.sh: the server template run failed, see $template/launch.log" >&2
    exit 1
  }
  rm -f "$template"/server.properties "$template"/launch.log
}

fetch_mods() {
  fetch "$FABRIC_API" "https://cdn.modrinth.com/data/P7dR8mSH/versions/6qAuTtLR/fabric-api-0.141.6%2B1.21.11.jar" \
    bdff7fd7e220085cfad2ff9b1f40dde6534ae0b96cf378f97a374bc54cb9ed0f
  fetch "$POLYMER" "https://cdn.modrinth.com/data/xGdtZczs/versions/wugBT1fU/polymer-bundled-0.15.2%2B1.21.11.jar" \
    2dfc65322e8ac7caed28cdd9a9836516c75fa880494112c03b4ee85ddccf44ed
  fetch "$FPL" "https://cdn.modrinth.com/data/8dI2tmqs/versions/nR8AIdvx/FabricProxy-Lite-2.11.0.jar" \
    ebc7abeaf6c03ac619c701ebb332de6966c6d83edfabf02434720c8fc3d03cdc
}

fetch_velocity() {
  fetch "$VELOCITY" \
    "https://fill-data.papermc.io/v1/objects/35a5596a5468a035d8a32c8de5ebb0dc6b8d8f0cc3ff5169d514aca762af8aa8/velocity-4.2.0-30.jar" \
    35a5596a5468a035d8a32c8de5ebb0dc6b8d8f0cc3ff5169d514aca762af8aa8
}

fetch_jre25() {
  if [ -n "$(ls -d "$CACHE"/jre25/*/bin/java 2>/dev/null)" ]; then
    return
  fi
  echo "fetch.sh: downloading a Temurin 25 JRE (Adoptium latest GA)"
  mkdir -p "$CACHE/jre25"
  curl -fsSL --retry 3 -o "$CACHE/jre25.tar.gz" "https://api.adoptium.net/v3/binary/latest/25/ga/linux/x64/jre/hotspot/normal/eclipse"
  tar -xzf "$CACHE/jre25.tar.gz" -C "$CACHE/jre25"
  rm -f "$CACHE/jre25.tar.gz"
}

targets=("$@")
[ ${#targets[@]} -gt 0 ] || targets=(server mods)
for target in "${targets[@]}"; do
  case $target in
    server) fetch_server ;;
    mods) fetch_mods ;;
    velocity) fetch_velocity ;;
    jre25) fetch_jre25 ;;
    *) echo "usage: fetch.sh [server] [mods] [velocity] [jre25]" >&2; exit 2 ;;
  esac
done
