#!/usr/bin/env bash
# Downloads the third-party files the e2e kit needs into E2E_CACHE (default e2e/work/cache). Every download is
# checked against a pinned SHA-256 and kept only if it matches. Idempotent: files that are already there with the right
# SHA-256 are kept. run_e2e.sh calls this itself.
#
#   fetch.sh [server] [mods] [velocity] [jre25] [viafabric] [polymer-real]       default: server mods
#
#   server        Fabric server launcher for 1.21.11 and E2E_LOADER (0.19.5 default; 0.19.3, 0.19.0 and 0.18.6 are
#                 pinned too), plus a server template: the launcher's first run downloads and remaps Minecraft, which
#                 every scenario then reuses, and downloads the Loader and its libraries from maven.fabricmc.net, which
#                 are checked against the SHA-256 pins below. Needs ACCEPT_EULA=true.
#   mods          Fabric API, Polymer (bundled), FabricProxy-Lite
#   velocity      Velocity 4.2.0 (needs Java 25)
#   jre25         a Temurin 25 JRE for Velocity (skipped if the cache has one, or VELOCITY_JAVA / JAVA is Java 25)
#   viafabric     ViaFabric 0.4.21+166 (bundles ViaVersion 5.10.0), for the V* scenarios
#   polymer-real  PolyDecorations and PolyFactory 0.10.4, real Polymer-based mods, for the PR* and PL2 scenarios
#
# Not covered by these pins: the Minecraft server jar and libraries the launcher downloads for the template (Mojang's
# manifest checksums apply), and the Gradle artifacts of the test mods (see README.md).
set -euo pipefail

E2E_PROG=fetch.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
e2e_defaults
CACHE=$E2E_CACHE
mkdir -p "$CACHE"

# fetch <file name in cache> <url> <sha256>
fetch() {
  local file=$CACHE/$1
  if [ -f "$file" ] && [ "$(sha256sum "$file" | cut -d' ' -f1)" = "$3" ]; then
    return
  fi
  echo "fetch.sh: downloading $1"
  curl -fsSL --retry 3 -o "$file.part" "$2"
  if [ "$(sha256sum "$file.part" | cut -d' ' -f1)" != "$3" ]; then
    rm -f "$file.part"
    echo "fetch.sh: checksum mismatch for $1 (downloaded from $2)" >&2
    exit 1
  fi
  mv "$file.part" "$file"
}

# The launcher is generated by meta.fabricmc.net for game 1.21.11, the loader and installer 1.1.2.
launcher_sha256() {
  case $1 in
    0.19.5) echo 2b63d293be54c8f5484a242859cab841dcee38511e11b2f82e92211f19872d08 ;;
    0.19.3) echo b855772f5a5d591262260e8ed3c218419366d74c3acfc38409f4a376f167051b ;;
    0.19.0) echo d8f57e11e602e989ce493146b321475b52039f19db1105623be30377e857665e ;;
    0.18.6) echo e727f9099270b63054fbf0a0f2733efb82161eb3c069509195a65d55d818471a ;;
    *) echo "fetch.sh: no pinned launcher for loader $1 (known: 0.19.5 0.19.3 0.19.0 0.18.6)" >&2; return 1 ;;
  esac
}

# The jars that the launcher downloads for a loader (the Loader, its mappings, Mixin and ASM) from maven.fabricmc.net,
# named by the server JSON of meta.fabricmc.net; the launcher itself checks no hash for them. "<path below libraries/>
# <sha256>" per line. Recorded from a download of every jar; the ASM jars and Mixin also match the sha256 fields of that
# server JSON, and the 0.19.5 jars are those of a template made by the pinned launcher.
loader_library_pins() {
  case $1 in
    0.19.5) cat <<'PINS'
org/ow2/asm/asm/9.10.1/asm-9.10.1.jar ed825d10ab1399c8c0cb669e688cf0c8c82629b4c8399b58352b68e92ca10fcb
org/ow2/asm/asm-analysis/9.10.1/asm-analysis-9.10.1.jar dede75a21306b65974ecd8f87114ff6970f09fb794157a4ca09ab25c888c2bfc
org/ow2/asm/asm-commons/9.10.1/asm-commons-9.10.1.jar 6d0abefb7cbf972ea16edb37ec14835372505063a45f976ab7ea889ed9497895
org/ow2/asm/asm-tree/9.10.1/asm-tree-9.10.1.jar 3dfb0d5b6a106cd40b5b250e39935fbf2f927f4477546a5369a3ac609cf0506b
org/ow2/asm/asm-util/9.10.1/asm-util-9.10.1.jar 1bb99d091fba2597dc6d51193e9bbcf0d8447e7ed96bd8f0198b18152f09655c
net/fabricmc/sponge-mixin/0.17.4+mixin.0.8.7/sponge-mixin-0.17.4+mixin.0.8.7.jar 1f0ae44db7295f8626f33b1dc0ad7f043d8954a8d6847247875fcc5dfcecc934
net/fabricmc/intermediary/1.21.11/intermediary-1.21.11.jar 886da9b21bf26b24a18960ec868612630821f161d7e8b23cd64bbaa51298cabc
net/fabricmc/fabric-loader/0.19.5/fabric-loader-0.19.5.jar 93044e4dd46de5d8136701292f05e868da096d2c9fddb4793e4fdbcc63efc695
PINS
      ;;
    0.19.3) cat <<'PINS'
org/ow2/asm/asm/9.10.1/asm-9.10.1.jar ed825d10ab1399c8c0cb669e688cf0c8c82629b4c8399b58352b68e92ca10fcb
org/ow2/asm/asm-analysis/9.10.1/asm-analysis-9.10.1.jar dede75a21306b65974ecd8f87114ff6970f09fb794157a4ca09ab25c888c2bfc
org/ow2/asm/asm-commons/9.10.1/asm-commons-9.10.1.jar 6d0abefb7cbf972ea16edb37ec14835372505063a45f976ab7ea889ed9497895
org/ow2/asm/asm-tree/9.10.1/asm-tree-9.10.1.jar 3dfb0d5b6a106cd40b5b250e39935fbf2f927f4477546a5369a3ac609cf0506b
org/ow2/asm/asm-util/9.10.1/asm-util-9.10.1.jar 1bb99d091fba2597dc6d51193e9bbcf0d8447e7ed96bd8f0198b18152f09655c
net/fabricmc/sponge-mixin/0.17.3+mixin.0.8.7/sponge-mixin-0.17.3+mixin.0.8.7.jar 9e90efec71d2bad5b96c9089f019d14a8603227d3c5f408d12f53fae89d99d41
net/fabricmc/intermediary/1.21.11/intermediary-1.21.11.jar 886da9b21bf26b24a18960ec868612630821f161d7e8b23cd64bbaa51298cabc
net/fabricmc/fabric-loader/0.19.3/fabric-loader-0.19.3.jar 73eed8c34bbad0320a2a3cba5346351e822f74f82b3f3c060574068474132958
PINS
      ;;
    0.19.0) cat <<'PINS'
org/ow2/asm/asm/9.9/asm-9.9.jar 03d99a74ad1ee5c71334ef67437f4ef4fe3488caa7c96d8645abc73c8e2017d4
org/ow2/asm/asm-analysis/9.9/asm-analysis-9.9.jar 6a15d28e8bd29ba4fd5bca4baf9b50e8fba2d7b51fbf78cfa0c875a7214c678b
org/ow2/asm/asm-commons/9.9/asm-commons-9.9.jar db2f6f26150bbe7c126606b4a1151836bcc22a1e05a423b3585698bece995ff8
org/ow2/asm/asm-tree/9.9/asm-tree-9.9.jar 42178f3775c9c63f9e5e1446747d29b4eca4d91bd6e75e5c43cfa372a47d38c6
org/ow2/asm/asm-util/9.9/asm-util-9.9.jar 3842e13cfe324ee9ab7cdc4914be9943541ead397c17e26daf0b8a755bede717
net/fabricmc/sponge-mixin/0.17.1+mixin.0.8.7/sponge-mixin-0.17.1+mixin.0.8.7.jar 855815cdfd685daf1a6c6ac391669754b805ce4e6ae1bc900ed29eedba48b806
net/fabricmc/intermediary/1.21.11/intermediary-1.21.11.jar 886da9b21bf26b24a18960ec868612630821f161d7e8b23cd64bbaa51298cabc
net/fabricmc/fabric-loader/0.19.0/fabric-loader-0.19.0.jar 97afcb471fdde8cca40de3f3fbcebb443711975573ef9a52bc80636c651305d4
PINS
      ;;
    0.18.6) cat <<'PINS'
org/ow2/asm/asm/9.9/asm-9.9.jar 03d99a74ad1ee5c71334ef67437f4ef4fe3488caa7c96d8645abc73c8e2017d4
org/ow2/asm/asm-analysis/9.9/asm-analysis-9.9.jar 6a15d28e8bd29ba4fd5bca4baf9b50e8fba2d7b51fbf78cfa0c875a7214c678b
org/ow2/asm/asm-commons/9.9/asm-commons-9.9.jar db2f6f26150bbe7c126606b4a1151836bcc22a1e05a423b3585698bece995ff8
org/ow2/asm/asm-tree/9.9/asm-tree-9.9.jar 42178f3775c9c63f9e5e1446747d29b4eca4d91bd6e75e5c43cfa372a47d38c6
org/ow2/asm/asm-util/9.9/asm-util-9.9.jar 3842e13cfe324ee9ab7cdc4914be9943541ead397c17e26daf0b8a755bede717
net/fabricmc/sponge-mixin/0.17.0+mixin.0.8.7/sponge-mixin-0.17.0+mixin.0.8.7.jar e7889fcd185e4199052dcbcf0fe2128581cbf8630aea7feb37429667b1ba49a9
net/fabricmc/intermediary/1.21.11/intermediary-1.21.11.jar 886da9b21bf26b24a18960ec868612630821f161d7e8b23cd64bbaa51298cabc
net/fabricmc/fabric-loader/0.18.6/fabric-loader-0.18.6.jar 2bc15285dde1d5b9ea3c8444d7063c60184c7e21883785e180f7a26e93772e41
PINS
      ;;
    *) echo "fetch.sh: no pinned libraries for loader $1" >&2; return 1 ;;
  esac
}

# verify_loader_libraries <template dir> <loader>: every jar above is there with its pinned SHA-256
verify_loader_libraries() {
  local template=$1 loader=$2 path sha bad=0
  while read -r path sha; do
    if [ "$(sha256sum "$template/libraries/$path" 2>/dev/null | cut -d' ' -f1)" != "$sha" ]; then
      echo "fetch.sh: libraries/$path in the server template is missing or does not match its pinned SHA-256 $sha" >&2
      bad=1
    fi
  done < <(loader_library_pins "$loader")
  return $bad
}


fetch_server() {
  local loader=$E2E_LOADER launcher sha template
  launcher=fabric-server-launch-1.21.11-$loader.jar
  sha=$(launcher_sha256 "$loader")
  fetch "$launcher" "https://meta.fabricmc.net/v2/versions/loader/1.21.11/$loader/1.1.2/server/jar" "$sha"
  template=$(template_dir)
  if [ -d "$template/libraries" ] && [ -d "$template/versions" ]; then
    if ! verify_loader_libraries "$template" "$loader"; then
      echo "fetch.sh: removing the server template $template; run fetch.sh again to build it anew" >&2
      rm -rf "$template"
      exit 1
    fi
    return
  fi
  if [ "${ACCEPT_EULA:-}" != "true" ]; then
    echo "fetch.sh: running a Minecraft server means accepting the Minecraft EULA (https://aka.ms/MinecraftEULA)." >&2
    echo "          Re-run with ACCEPT_EULA=true if you accept it." >&2
    exit 1
  fi
  echo "fetch.sh: preparing the server template for loader $loader (downloads and remaps Minecraft 1.21.11, takes a minute)"
  rm -rf "$template"
  mkdir -p "$template"
  local default_template=$CACHE/server-template
  if [ "$loader" != "$DEFAULT_LOADER" ] && [ -d "$default_template/libraries" ]; then
    # Start from the default loader's template (Mojang's server jar and the vanilla libraries are already there) and
    # drop everything that belongs to that loader.
    cp -a "$default_template/." "$template/"
    rm -rf "$template/logs" "$template/.fabric/remappedJars" "$template/.fabric/processedMods" "$template"/.fabric/server/fabric-loader-server-*
  fi
  cp "$CACHE/$launcher" "$template/fabric-server-launch.jar"
  echo "eula=true" > "$template/eula.txt"
  # --initSettings makes the server write its settings files and exit before it loads a world.
  (cd "$template" && "$JAVA" -jar fabric-server-launch.jar nogui --initSettings > launch.log 2>&1 < "$E2E_STDIN") || {
    echo "fetch.sh: the server template run failed, see $template/launch.log" >&2
    exit 1
  }
  rm -rf "$template/server.properties" "$template/launch.log" "$template/logs"
  if ! verify_loader_libraries "$template" "$loader"; then
    echo "fetch.sh: removing the server template $template" >&2
    rm -rf "$template"
    exit 1
  fi
}

fetch_mods() {
  fetch "$FABRIC_API" "https://cdn.modrinth.com/data/P7dR8mSH/versions/6qAuTtLR/fabric-api-0.141.6%2B1.21.11.jar" \
    bdff7fd7e220085cfad2ff9b1f40dde6534ae0b96cf378f97a374bc54cb9ed0f
  fetch "$POLYMER" "https://cdn.modrinth.com/data/xGdtZczs/versions/wugBT1fU/polymer-bundled-0.15.2%2B1.21.11.jar" \
    2dfc65322e8ac7caed28cdd9a9836516c75fa880494112c03b4ee85ddccf44ed
  fetch "$FPL" "https://cdn.modrinth.com/data/8dI2tmqs/versions/nR8AIdvx/FabricProxy-Lite-2.11.0.jar" \
    ebc7abeaf6c03ac619c701ebb332de6966c6d83edfabf02434720c8fc3d03cdc
}

fetch_velocity() {
  fetch "$VELOCITY" \
    "https://fill-data.papermc.io/v1/objects/35a5596a5468a035d8a32c8de5ebb0dc6b8d8f0cc3ff5169d514aca762af8aa8/velocity-4.2.0-30.jar" \
    35a5596a5468a035d8a32c8de5ebb0dc6b8d8f0cc3ff5169d514aca762af8aa8
}

fetch_jre25() {
  if [ -n "$(ls -d "$CACHE"/jre25/*/bin/java 2>/dev/null)" ]; then
    return
  fi
  local tarball=temurin-jre-25.0.4.1_1.tar.gz
  fetch "$tarball" \
    "https://github.com/adoptium/temurin25-binaries/releases/download/jdk-25.0.4.1%2B1/OpenJDK25U-jre_x64_linux_hotspot_25.0.4.1_1.tar.gz" \
    1731a34baadec5479258ea0202e4d5d865d2efeee60cb0c7d7eb056fe96ca219
  rm -rf "$CACHE/jre25"
  mkdir -p "$CACHE/jre25"
  tar -xzf "$CACHE/$tarball" -C "$CACHE/jre25"
  rm -f "$CACHE/$tarball"
}

fetch_viafabric() {
  # Modrinth version MRUUxfWz. 0.4.21+166 is the newest ViaFabric build for 1.21.11 that starts on Java 21 and 25.
  fetch "$VIAFABRIC" "https://cdn.modrinth.com/data/YlKdE5VK/versions/MRUUxfWz/ViaFabric-0.4.21%2B166-1.14-1.21.jar" \
    aa0e19d929913cbb276e7732fed06997d777e2a129580dded7443f2fb0f0327f
}

fetch_polymer_real() {
  # Modrinth projects 5710VC7f (version HznHHrk4) and MikpSrAF (version E7XbHhGB)
  fetch "$POLYDECORATIONS" "https://cdn.modrinth.com/data/5710VC7f/versions/HznHHrk4/polydecorations-0.10.4%2B1.21.11.jar" \
    973843bec8af8890b13786e9114d9b4abd7fe046d12c83c48dad0f992f3897a9
  fetch "$POLYFACTORY" "https://cdn.modrinth.com/data/MikpSrAF/versions/E7XbHhGB/polyfactory-0.10.4%2B1.21.11.jar" \
    c1e2c84d4a9a8595dcb324d87790f862934e7acab27d57d8d9b56ee8691eee8d
}

targets=("$@")
[ ${#targets[@]} -gt 0 ] || targets=(server mods)
for target in "${targets[@]}"; do
  case $target in
    server) fetch_server ;;
    mods) fetch_mods ;;
    velocity) fetch_velocity ;;
    jre25) fetch_jre25 ;;
    viafabric) fetch_viafabric ;;
    polymer-real) fetch_polymer_real ;;
    *) echo "usage: fetch.sh [server] [mods] [velocity] [jre25] [viafabric] [polymer-real]" >&2; exit 2 ;;
  esac
done
